/**
 * This file is auto-generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * To update, run 'bun router middleware:map'
 */

import { LoggerMiddleware } from 'examples/middleware/LoggerMiddleware'
import { ExampleMiddleware } from 'examples/middleware/ExampleMiddleware'

/**
 * Map of all available middleware in the project
 */
export interface MiddlewareMap {
  LoggerMiddleware: typeof LoggerMiddleware
  ExampleMiddleware: typeof ExampleMiddleware
}

/**
 * Type representing all available middleware classes in the project
 */
export type MiddlewareType = LoggerMiddleware | ExampleMiddleware

/**
 * Type for a middleware handler function
 */
export type MiddlewareHandler = (req: any, next: () => Promise<Response>) => Promise<Response>

/**
 * Ensure the middleware module exports all the middleware classes used in the project
 */
export const middlewareMap: MiddlewareMap = {
  LoggerMiddleware: LoggerMiddleware,
  ExampleMiddleware: ExampleMiddleware
}
